### PR TITLE
Datadict meta

### PR DESCRIPTION
**Pull request by swanijam**
The history for this one is gonna be a little weird, because it was taken off of the master branch after datadict was added. Datadict was then removed from this branch so it could be isolated in its own branch. The result is a commit in this branch that says 'Add datadict generator'.

### CODE REVIEW

**Comment by bruth** [comment]
This PR's parent is the datadict generator. This must be rebased against master for them to be separate feature branches.

**Comment by bruth** [comment]
This branch still needs to be rebased against the recent changes in upstream master (they needed to be fetched and then this branch rebased). Also the committed `.swp` file needs to be removed.

**Comment by bruth** [comment]
Sorry, I think we misunderstood one another. When you said "filesystem", I presumed you were working on the filesystem-based generator. The facts being generated here should be about the structure of the data dictionary format itself, not the file on the filesystem. For example, the "meta facts" for a data dictionary like this:

| Identifier | Name | Type | Unique |
| --- | --- | --- | --- |
| 1 | ID | integer | true |
| 2 | Username | string | true |
| 3 | Email | string | true |
| 4 | Quote | string | false |

would only inspect the header:

| entity | attribute_domain | attribute | value |
| --- | --- | --- | --- |
| Identifier | origins.attrs | label | Identifier |
| Identifier |  | index | 0 |
| Name | origins.attrs | label | Name |
| Name |  | index | 1 |
| Type | origins.attrs | label | Type |
| Type |  | index | 2 |
| Unique | origins.attrs | label | Unique |
| Unique |  | index | 3 |

Thinking about this more, this is exactly what the `delimited` generator does, so there is no need to create a datadict-meta generator. If a user wants to create meta facts about a datadict, they can just use that.

**Comment by swanijam** [comment]
Then I think I'm confused. What is the difference between delimited and datadict? does delimited need a meta/data generator or is it itself the meta generator of a datadict?

**Comment by bruth** [comment]
Nope, there is no need for a datadict meta generator. A data dictionary has the structure each _row_ defines a field that is in a data model (for example a REDCap project). However, the data dictionary header defines the fields used to describe the data model being defined (e.g. `Variable / Identifier`). Obviously because we only have a header to extract information from, the facts are pretty sparse.

**Comment by swanijam** [comment]
oh okay so there will be a delimited-data and a delimited-meta, and the delimited-meta happens to describe the datadict-meta very well.

**Comment by bruth** [comment]
Correct. We happen to know the "data" in a data dict is simply a description of another data model. The meta facts are the description of the structure for the contained data.

**Comment by bruth** [comment]
To put it concretely the meta generated output is a set of entities that are the attributes used in the data generated output.

**Comment by bruth** [comment]
To prevent confusion we should start referring to it as a schema generator rather than a meta generator.

**Pull request closed without merging**
